---
- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload systemd-networkd
  become: true
  ansible.builtin.systemd:
    name: systemd-networkd.service
    state: reloaded
