#cloud-config
users:
  - name: "${user}"
    groups: [adm, audio, cdrom, dialout, dip, floppy, plugdev, sudo, video]
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash
    plain_text_passwd: "${user}"
    lock_passwd: false
    ssh_authorized_keys:
      - "${ssh_authorized_key}"

runcmd:
  - sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
  - locale-gen
  - netplan apply
  - systemctl restart systemd-networkd.service

write_files:
  - path: /etc/locale
  - path: /etc/udev/rules.d/70-persistent-net.rules
    content: |
      ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="${mgmt_mac}", NAME="eth0", SUBSYSTEMS=="pci"
%{ for link in links ~}
      ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="${link.src_mac}", NAME="${link.src_port}", SUBSYSTEMS=="pci"
%{ endfor ~}
