---
- name: Install lldpd
  become: true
  ansible.builtin.apt:
    name: lldpd

- name: Service lldpd
  become: true
  ansible.builtin.systemd:
    name: lldpd.service
    state: started
    enabled: true

- name: Sysctl net
  become: true
  ansible.builtin.copy:
    content: |
      # Enable IPv4/IPv6 forwarding
      net.ipv4.ip_forward=1
      net.ipv6.conf.default.forwarding=1
      net.ipv6.conf.all.forwarding=1
      # Enable ECMP L4 flow hashing
      net.ipv4.fib_multipath_hash_policy=1
      net.ipv6.fib_multipath_hash_policy=1
      net.ipv4.fib_multipath_use_neigh=1
    dest: /etc/sysctl.d/30-networking.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Sysctl reload
