---
istio_ingress_version: 1.20.3
istio_ingress_istioctl_url: https://storage.googleapis.com/istio-release/releases/{{ istio_ingress_version }}/istio-{{ istio_ingress_version }}-linux-amd64.tar.gz
istio_ingress_istioctl_checksum: sha256:2ee49f838a75e9fc9a22a89f17134042051bdacab826eea25a6b7d26803f7e6b
istio_ingress_ipv6_enabled: false
istio_ingress_discovery_address: istiod.istio-system.svc:15012

istio_ingress_sidecar_url: https://storage.googleapis.com/istio-release/releases/{{ istio_ingress_version }}/deb/istio-sidecar.deb
istio_ingress_sidecar_checksum: sha256:91cab3e83800ad15455c1b202900df9a4f7ca6cfcbe3545e92baa1a1e460185c
